# Hexo 配置
## 文档: https://hexo.io/zh-cn/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 网站
title: GuDu-Blog
subtitle: ''
description: ''
keywords:
# author: John Doe
language: en
timezone: ''

# 网址
## 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，则请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/
url: https://guguyili.us.kg/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # 设为 false 来去掉永久链接尾部的 index.html
  trailing_html: true # 设为 false 来去掉永久链接尾部的 .html

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md # 新文章的文件名称
default_layout: post
titlecase: false # 将标题转换为 title case
external_link:
  enable: true # 在新标签中打开链接
  field: site # 对整个网站生效
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# 主页设置
# path: 博客索引页的根路径。（默认 = ''）
# per_page: 每页显示的文章量 (0 = 关闭分页功能)
# order_by: 文章排序方式 (默认按日期降序排列)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/meta
meta_generator: true

# 日期 / 时间格式
## Hexo 使用 Moment.js 来解析和显示日期
## 您可以根据 http://momentjs.com/docs/#/displaying/format/ 来修改日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option 支持 'mtime', 'date', 'empty'
updated_option: 'mtime'

# 分页
## 设置每页显示的文章数量，设为 0 表示关闭分页功能
per_page: 10
pagination_dir: page

# 包括 / 排除 文件
## include:/exclude: 选项只对 'source/' 文件夹有效
include:
exclude:
ignore:

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: flexblock

# 部署
## 文档: https://hexo.io/zh-cn/docs/one-command-deployment
deploy:
  type: ''


# 页头
menu:
  Home:/

# 主页 banner 图
banner:

# 站点通知信息
notice:

# 作者信息
author: 
  name: Guduyili
  avatar:
  description:

# 目录
toc:
  max_depth: 3 # 生成目录的最大深度
  min_depth: 2 # 生成目录的最小深度

# 评论
comments:
  enable: true
  use: 'valine' # valine 或 disqus
  # valine 评论
  # 文档: https://valine.js.org
  # 您可以从 https://leancloud.cn 获取您的 appid 和 appkey
  # 这里的 appId 和 appKey 一定要改成自己的，没有的话去 https://leancloud.cn 这个网站注册创建一个
  valine:
    appId:
    appKey:
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: true
    visitor: true
    pageSize: 10
  # disqus 评论
  # 文档: https://disqus.com/
  disqus:
    website:
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放器
# 文档: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放器
# 文档: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: UA-165681463-1
# gauges 分析
gauges_analytics: 
# 百度分析
baidu_analytics: 77cce6624f1114785af5e77d00cbf93c
# 腾讯分析
tencent_analytics: 66537616
# 站点图标
favicon: /favicon.ico

# 社交图标
social_icon:
  enable: true
  icons:
    ins     :
    zhihu   :
    weibo   :  
    github  : https://github.com/guduyili
    twitter :