# Hexo 配置
## 文档: https://hexo.io/zh-cn/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 网站
title: GuDu-Blog
subtitle: ''
description: ''
keywords:
language: en
timezone: ''

# 网址
url: https://guguyili.us.kg/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false  # ✅ 关闭独立资源文件夹（全局管理图片）
relative_link: false
future: true
syntax_highlighter: prismjs
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true

# 主页设置
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
meta_generator: true

# 日期 / 时间格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# 分页
per_page: 10
pagination_dir: page

# 包括 / 排除 文件
include:
exclude:
ignore:

# 扩展
theme: flexblock

# 部署
deploy:
  type: ''

# 页头
menu:
  Home: /

# 主页 banner 图
banner:

# 站点通知信息
notice:

# 作者信息
author: 
  name: Guduyili
  avatar:
  description:

# 目录
toc:
  enable: true
  max_depth: 3
  min_depth: 2

# 评论
comments:
  enable: true
  use: 'valine'
  valine:
    appId:
    appKey:
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: true
    visitor: true
    pageSize: 10
  disqus:
    website:
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# DPlayer 视频播放器
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# APlayer 音频播放器
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 分析统计
google_analytics: UA-165681463-1
gauges_analytics: 
baidu_analytics: 77cce6624f1114785af5e77d00cbf93c
tencent_analytics: 66537616

# 站点图标
favicon: /favicon.ico

# 社交图标
social_icon:
  enable: true
  icons:
    ins     :
    zhihu   :
    weibo   :  
    github  : https://github.com/guduyili
    twitter :

# Markdown 解析器配置
marked:
  prependRoot: true
  postAsset: true

# Lazyload 图片懒加载
lazyload:
  enable: true
  field: post
  loadingImg: /img/friend_404.gif
  preloadRatio: 1

# 插件配置：hexo-asset-image
asset_image:
  path: img  # ✅ 全局图片目录为 source/img