name: Hexo deploy

on: 
  push:
    paths-ignore:
      - 'source/_GoNotes/**'
      - 'source/_JavaNotes/**'
      - 'source/_PythonNotes/**'
      - 'source/_drafts/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16  # 指定 Node.js 16（满足 hexo-cli >=14 的要求
    
    - name: Cache node modules
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "Cache not hit, installing dependencies..."
        npm ci
        
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
        deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }}
        user_name: guduyili
        user_email: LZY3376163189@163.com
        commit_msg: ${{ github.event.head_commit.message }}
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.3.1  # 可根据实际情况替换为最新稳定版本
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        with:
          # 源仓库
          source-repo: git@github.com:guduyili/GDYL-Blog.git
          # 目标仓库
          destination-repo: git@gitee.com:Absolutelynothing/GDYL-Blog.git
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: 后藤一里 # 替换为实际的 Gitee 用户名
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: 后藤一里/GDYL-Blog # 替换为实际的 Gitee 仓库名
          branch: master