name: Hexo Deploy & Sync

on:
  push:
    paths-ignore:
      - 'source/_GoNotes/**'
      - 'source/_JavaNotes/**'
      - 'source/_PythonNotes/**'
      - 'source/_drafts/**'
      - '.github/**'

jobs:
  build_and_deploy:
    name: Build Hexo Site & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Clean Install
        run: |
          npm ci --ignore-scripts
          npm config set unsafe-perm true
          npm rebuild

          
      - name: Build Hexo Site
        run: |
          npx hexo clean
          npx hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy: ${{ github.sha }}"

  sync_to_gitee:
    name: Sync to Gitee
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        with:
          source-repo: git@github.com:guduyili/GDYL-Blog.git
          destination-repo: git@gitee.com:Absolutelynothing/GDYL-Blog.git

  trigger_gitee_pages:
    name: Build Gitee Pages
    needs: sync_to_gitee
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pages
        uses: mizuka-wu/gitee-pages-action@v2.0
        with:
          gitee-username: 后藤一里
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          repo: 后藤一里/GDYL-Blog
          branch: main
